import { useEffect, useState } from "react";
import "./Settings.css";

import {
  GetOutputDirectory,
  SetOutputDirectory,
  OpenDir,
} from "../../wailsjs/go/main/App";

function Settings({ onHome }) {
  const [outputDirectory, setOutputDirectory] = useState("");
  const [status, setStatus] = useState("idle");
  const [feedback, setFeedback] = useState("");

  useEffect(() => {
    GetOutputDirectory()
      .then(setOutputDirectory)
      .catch((error) => {
        console.error("Failed to load output directory:", error);
        setStatus("error");
        setFeedback(error?.message || String(error));
      });
  }, []);

  async function handleChangeOutputDirectory() {
    setStatus("loading");
    setFeedback("");

    try {
      const path = await SetOutputDirectory();

      if (!path) {
        setStatus("idle");
        return;
      }

      setOutputDirectory(path);
      setStatus("success");
      setFeedback("Output directory updated");
    } catch (error) {
      console.error("Failed to change output directory:", error);

      setStatus("error");
      setFeedback(error?.message || String(error));
    }
  }

  async function handleOpenOutputDirectory() {
    if (!outputDirectory) {
      setStatus("error");
      setFeedback("No output directory configured");
      return;
    }

    setStatus("loading");
    setFeedback("");

    try {
      await OpenDir(outputDirectory);

      setStatus("success");
      setFeedback("Output folder opened successfully");
    } catch (error) {
      console.error("Failed to open output directory:", error);

      setStatus("error");
      setFeedback(error?.message || String(error));
    }
  }

  return (
    <main className="settings">
      <button className="payslip-back" onClick={onHome}>
        ← Back
      </button>

      <header className="settings-header">
        <h1>Settings</h1>
        <p>Manage application settings.</p>
      </header>

      <section className="settings-section">
        <h2>Output Directory</h2>

        <p className="settings-description">
          Payslips generated by the application will be saved here.
        </p>

        <div className="settings-path">
          {outputDirectory || "No output directory configured"}
        </div>

        <div className="settings-actions">
          <button
            className="settings-action"
            onClick={handleChangeOutputDirectory}
            disabled={status === "loading"}
          >
            {status === "loading" ? "Choosing..." : "Change Output Folder"}
          </button>

          <button
            className="settings-action"
            onClick={handleOpenOutputDirectory}
            disabled={status === "loading" || !outputDirectory}
          >
            Open Output Folder
          </button>
        </div>

        {status !== "idle" && feedback && (
          <div className={`settings-feedback ${status}`}>{feedback}</div>
        )}
      </section>
    </main>
  );
}

export default Settings;
