// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEmployees() {
  return window['go']['main']['App']['GetEmployees']();
}

export function GetPayslip(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPayslip'](arg1, arg2, arg3);
}
