// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetEmployees():Promise<Array<models.Employee>>;

export function GetPayslip(arg1:string,arg2:number,arg3:number):Promise<models.PayslipExport>;
