// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseOutputDirectory() {
  return window['go']['main']['App']['ChooseOutputDirectory']();
}

export function GenerateMonthlyPayslip(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateMonthlyPayslip'](arg1, arg2, arg3);
}

export function GenerateMonthlyPayslips(arg1, arg2) {
  return window['go']['main']['App']['GenerateMonthlyPayslips'](arg1, arg2);
}

export function GenerateYearlyPayslip(arg1, arg2) {
  return window['go']['main']['App']['GenerateYearlyPayslip'](arg1, arg2);
}

export function GenerateYearlyPayslips(arg1) {
  return window['go']['main']['App']['GenerateYearlyPayslips'](arg1);
}

export function GetEmployee(arg1) {
  return window['go']['main']['App']['GetEmployee'](arg1);
}

export function GetEmployees() {
  return window['go']['main']['App']['GetEmployees']();
}

export function GetEmployeesBySchool(arg1) {
  return window['go']['main']['App']['GetEmployeesBySchool'](arg1);
}

export function GetOutputDirectory() {
  return window['go']['main']['App']['GetOutputDirectory']();
}

export function GetPayslip(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPayslip'](arg1, arg2, arg3);
}

export function GetSchool(arg1) {
  return window['go']['main']['App']['GetSchool'](arg1);
}

export function GetSchoolsByCluster(arg1) {
  return window['go']['main']['App']['GetSchoolsByCluster'](arg1);
}

export function GetYearlyPayslip(arg1, arg2) {
  return window['go']['main']['App']['GetYearlyPayslip'](arg1, arg2);
}

export function SetOutputDirectory() {
  return window['go']['main']['App']['SetOutputDirectory']();
}
